steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["./gradlew", "bootBuildImage"]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/playground-311121/storedemo:latest"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernetes-resource-file
  - --image=gcr.io/playground-311121/storedemo:latest
  - --location=us-central1
  - --cluster=autopilot-cluster-1

