steps:
- name: gradle:8.0.2-jdk17
  entrypoint: gradle
  args: ['bootBuildImage', '--publishImage', '--imageName', 'gcr.io/playground-311121/storedemo:0.0.1-SNAPSHOT']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=k8s.yaml
  - --image=gcr.io/playground-311121/storedemo:0.0.1-SNAPSHOT
  - --location=us-central1
  - --cluster=autopilot-cluster-1

