steps:
- name: gradle:8.0.2-jdk17
  entrypoint: gradle
  args: ['bootBuildImage']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=k8s.yaml
  - --image=docker.io/library/store-demo:0.0.1-SNAPSHOT
  - --location=us-central1
  - --cluster=autopilot-cluster-1

