apiVersion: apps/v1
kind: Deployment
metadata:
  name: storedemo
spec:
  selector:
    matchLabels:
      run: storedemo
  template:
    metadata:
      labels:
        run: storedemo
    spec:
      containers:
      - name: storedemo
        image: gcr.io/playground-311121/storedemo:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: storedemo
  labels:
    run: storedemo
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    run: storedemo

